trigger:
  - master

# Это задаёт версию NuGet-пакета: 1.0.1.1, 1.0.1.2 и т.д.
name: 1.0.1.$(Rev)

pool:
  name: Default  # Self-hosted agent

variables:
  buildConfiguration: 'Release'

steps:
  - task: UseDotNet@2
    displayName: 'Install .NET 8 SDK'
    inputs:
      packageType: 'sdk'
      version: '8.0.x'
      installationPath: $(Agent.ToolsDirectory)/dotnet

  - task: DotNetCoreCLI@2
    displayName: 'Restore .NET Packages'
    inputs:
      command: 'restore'
      projects: '**/*.csproj'

  - task: DotNetCoreCLI@2
    displayName: 'Build Project'
    inputs:
      command: 'build'
      projects: '**/*.csproj'
      arguments: '--configuration $(buildConfiguration)'

  - task: DotNetCoreCLI@2
    displayName: 'Pack NuGet package'
    inputs:
      command: 'pack'
      packagesToPack: '**/StringExtensions.csproj'
      versioningScheme: 'byBuildNumber'
      configuration: 'Release'
      outputDir: '$(Build.ArtifactStagingDirectory)'

  - task: NuGetCommand@2
    displayName: 'Push to Azure Artifacts'
    inputs:
      command: 'push'
      packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
      publishVstsFeed: 'TamirlanBaidauletovLab4/lab4feed'
